### ISSUE TITLE
rule within media query not overriding other rule

### ISSUE THREAD

**Issue by jmlee2k** [rodneyrehm/viewport-units-buggyfill#52]
First of all, thanks a TON for this!  It definitely spared me at least a couple grey hairs.

Not sure if this is a bug or not, but I thought I would mention it here in case anyone runs into it.  If you have a standard rule, something like:
```css
.sidebar
{
    flex-basis: 80vmax;
}
```
and a rule within a media query which overrides it:
```css
@media all and (orientation:portrait)
{
    .sidebar
    {
        flex-basis: auto;
    }
}
```
the "auto" won't take effect when the media query is active.  In this case, the easy workaround is to just specify both flex-basis values in their own media queries as follows:
```css
@media all and (orientation:landscape)
{
    .sidebar
    {
        flex-basis: 80vmax;
    }
}

@media all and (orientation:portrait)
{
    .sidebar
    {
        flex-basis: auto;
    }
}
```
Again, thanks a lot to everyone that's worked on this, and I hope this helps out!
