### ISSUE TITLE
Bug on img

### ISSUE THREAD

**Issue by fabbrikk** [rodneyrehm/viewport-units-buggyfill#61]
When appling on an img tag something like this:
```css
#div img{
	max-height: 40vh;
	content: 'viewport-units-buggyfill; max-height: 40vh;';
}
```
the img disapear.
A workaround can be use moodernizr to inject cssvhunit class to html, and then in css add this rule:
```css
.cssvhunit #div img{
	content: normal !important;
}
```
