### ISSUE TITLE
This doesn't seem to work with sass variables

### ISSUE THREAD

**Issue by rootion** [rodneyrehm/viewport-units-buggyfill#65]
Do we necessarily have to include here the final value? 
I am notifying that the bugyfill doesn't work with sass variables. 

Something like: 
```
  margin-top: $header-height-small;
  width: $content-width-small;
  max-width: $content-width-small;
  height: $content-height-small;
  /* Viewport-units-buggyfill.js */
   content: 'viewport-units-buggyfill; margin-top: $header-height-small; width: $content-width-small; max-width: $content-width-small; height: $content-height-small;';
```

Is it possible to include sass variables in this bugyfill?

**Comment by rodneyrehm** [comment]
What you're looking for is called [interpolation](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#interpolation_):

```scss
  margin-top: $header-height-small;
  width: $content-width-small;
  max-width: $content-width-small;
  height: $content-height-small;
  /* Viewport-units-buggyfill.js */
   content: 'viewport-units-buggyfill; margin-top: #{$header-height-small}; width: #{$content-width-small}; max-width: #{$content-width-small}; height: #{$content-height-small};';
```

This has got nothing to do with the buggyfill. Interpolation is a Sass thing.
