### ISSUE TITLE
How do you use viewport-units-buggyfill in the pseudo-element?

### ISSUE THREAD

**Issue by airen** [rodneyrehm/viewport-units-buggyfill#95]
@rodneyrehm ，How do you use viewport-units-buggyfill in the pseudo-element? eg: sometimes, I use pseudo-element to make ICONS.

Input CSS

```css
.icon-book::before {
      content: 'book';
      width: 2vw;
      height: 2vw;
}
```

Output CSS

```
.icon-book::before {
   content: 'viewport-units-buggyfill; width: 2vw;height: 2vw;`
}
```
